### ISSUE TITLE
Question/Reply count error

### ISSUE THREAD

**Issue by ishir21** [CerritusCodersComm/eduJam#48]
In the forum if you ask a question or reply to a question , the number gets incremented in your profile .
If the user deletes his/her question or reply the number gets decremented .
The question/reply count goes below 0 if the user deletes more questions/replies than they asked.

Hint: A simple conditional statement at the right place will solve this issue.

Files to look into: 
https://github.com/CerritusCodersComm/eduJam/blob/main/app/src/main/java/com/example/gdsc_hackathon/adapters/QuestionAdapter.kt
https://github.com/CerritusCodersComm/eduJam/blob/main/app/src/main/java/com/example/gdsc_hackathon/adapters/ReplyAdapter.kt

**Comment by kostonkiddo10** [comment]
Created a Pull Request. Should be fixed but couldn't fully check since I'm not a TCET student.

**Comment by cdhiraj40** [comment]
hey @kostonkiddo10, thanks for taking the initiative, I will mail you the test credentials :)

**Comment by kostonkiddo10** [comment]
hey there @cdhiraj40! I was able to test the code, the question and reply count no longer goes negative. #54 pull request should fix it for everyone, so please review and let me know! :) 

I have one concern though. The app is counting questions and replies that you post incorrectly I believe since there was a question that was posted by the test account but the counter was still at 0. Is there already an issue created about this?

**Comment by cdhiraj40** [comment]
> hey there @cdhiraj40! I was able to test the code, the question and reply count no longer goes negative. #54 pull request should fix it for everyone, so please review and let me know! :) 

@kostonkiddo10 thanks for the test, i will check your PR as soon as possible


> I have one concern though. The app is counting questions and replies that you post incorrectly I believe since there was a question that was posted by the test account but the counter was still at 0. Is there already an issue created about this?

I actually know about this and it was done by me to test it out, i asked the question from phone/account and then deleted the question from console so the number went from -2 to 0 and never got decreased because of deleting from console. So as far as i know there is no problem there :)

.

**Comment by kostonkiddo10** [comment]
@cdhiraj40 Sounds great! No worries then. :)

**Comment by cdhiraj40** [comment]
fixed by #54
